include: package:leancode_lint/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - 'lib/l10n/output/*.dart'

linter:
  rules:
    always_put_control_body_on_new_line: false
