name: aw_pilot_helper
publish_to: 'none'

environment:
  sdk: ^2.17.0

dependencies:
  collection: ^1.17.0
  either_dart: ^0.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_markdown: ^0.6.14
  freezed_annotation: ^2.2.0
  intl: ^0.18.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  leancode_lint: ^2.1.0+1

flutter:
  uses-material-design: true

  assets:
  - assets/about.md
