name: aw_pilot_helper
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^2.17.0

dependencies:
  collection: ^1.17.0
  dio: ^5.1.1
  either_dart: ^0.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  mask_text_input_formatter: ^2.4.0
  provider: ^6.0.5
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  leancode_lint: ^2.1.0+1
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
  - assets/about.md
