# fly.toml file generated for aw-pilot-helper on 2023-04-08T21:16:53+02:00

app = "aw-pilot-helper"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ams"
processes = []

[env]
  PORT = "8080"
  NODE_ENV = "production"
  APP_URL = "https://aw-pilot-helper.fly.dev"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
