# https://github.com/fastlane/fastlane/issues/21125#issuecomment-1473306222
require 'spaceship'
Spaceship::ConnectAPI::App.const_set('ESSENTIAL_INCLUDES', 'appStoreVersions')

default_platform(:ios)

platform :ios do
  desc "Submit a new production build to App Store"
  lane :production do
    build_number = ENV["BUILD_NUMBER"] != nil ? "--build-number #{ENV["BUILD_NUMBER"]}" : ''

    setup_ci if ENV['CI']

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    match(type: "development") # Passed in Xcode
    match(type: "appstore")

    sh "flutter build ipa --release #{build_number} " +
      "--dart-define API_URL=#{ENV['API_URL']} --dart-define API_TOKEN=#{ENV['API_TOKEN']}"

    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )

    version_number = get_version_number()
    build_number = get_build_number()
    sh "echo built-version='#{version_number}+#{build_number}' >> $GITHUB_OUTPUT" if ENV["GITHUB_OUTPUT"]

    upload_to_app_store(
      force: true,
      submit_for_review: true,
      automatic_release: true,
      skip_metadata: true,
      precheck_include_in_app_purchases: false,
    )
  end
end
