# https://github.com/fastlane/fastlane/issues/21125#issuecomment-1473306222
require 'spaceship'
Spaceship::ConnectAPI::App.const_set('ESSENTIAL_INCLUDES', 'appStoreVersions')

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_number = ENV["BUILD_NUMBER"] != nil ? "--build-number #{ENV["BUILD_NUMBER"]}" : ''

    setup_ci if ENV['CI']

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    match(type: "development") # Passed in Xcode
    match(type: "appstore")

    sh "flutter build ipa --release #{build_number}"
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
    )
  end
end
