default_platform(:android)

platform :android do
  desc "Submit a new production build to Google Play"
  lane :production do
    build_number = ENV["BUILD_NUMBER"] != nil ? "--build-number #{ENV["BUILD_NUMBER"]}" : ''

    sh "flutter build appbundle --release #{build_number}"

    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
      skip_upload_metadata: true,
    )
  end
end
