require 'yaml'

default_platform(:android)

platform :android do
  desc "Submit a new production build to Google Play"
  lane :production do
    build_number = ENV["BUILD_NUMBER"] != nil ? "--build-number #{ENV["BUILD_NUMBER"]}" : '1'

    sh "flutter build appbundle --release #{build_number} " +
      "--dart-define API_URL=#{ENV['API_URL']} --dart-define API_TOKEN=#{ENV['API_TOKEN']}"

    version_number = YAML.load_file('../../pubspec.yaml')['version'].split(/\+/, 2).first
    sh "echo built-version='#{version_number}+#{build_number}' >> $GITHUB_OUTPUT" if ENV["GITHUB_OUTPUT"]

    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
      skip_upload_metadata: true,
    )
  end
end
