name: Deploy app (iOS, App Store)

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  ios:
    runs-on: macos-latest

    needs: [test]

    defaults:
      run:
        working-directory: ios

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.x'

      - name: Flutter version
        run: flutter --version

      - name: Download pub dependencies
        run: flutter pub get

      - name: Cache bundle dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Decrypt assets
        run: ../assets.sh decrypt $PASSWORD
        env:
          PASSWORD: ${{ secrets.ASSETS_DECRYPT_PASSWORD }}

      - name: Download bundle dependencies
        run: |
          gem install bundler:2.3.23
          bundle config path vendor/bundle
          bundle install

      - name: Run fastlane
        id: deploy
        env:
          API_URL: ${{ vars.API_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          MATCH_GIT_URL: ${{ vars.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: bundle exec fastlane production

      - name: Push tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ios-${{ steps.deploy.outputs.built-version }}
