name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.x'

      - name: Flutter version
        run: flutter --version

      - name: Download pub dependencies
        run: flutter pub get

      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      - name: Run analyze
        run: flutter analyze
        if: always()

      - name: Run tests
        run: flutter test
        if: always()
